language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install -r requirements26.txt; fi
  - pip install --use-mirrors -r requirements.txt
  - python setup.py develop
script: nosetests tests/unit
